"""Add Korean table and column comments

Revision ID: 86e220a2e6c0
Revises: 
Create Date: 2026-01-17 13:37:30.886770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '86e220a2e6c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividends_dividend_date'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_stock_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_user_id'), table_name='dividends')
    op.drop_table('dividends')
    op.alter_column('batch_job_status', 'id',
               existing_type=sa.INTEGER(),
               comment='작업 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('batch_job_status', 'job_name',
               existing_type=sa.VARCHAR(length=100),
               comment='작업명 (예: daily_pnl_calculation)',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'),
               comment='작업 상태 (PENDING/RUNNING/SUCCESS/FAILED)',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='작업 시작일시',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='작업 완료일시',
               existing_nullable=True)
    op.alter_column('batch_job_status', 'records_processed',
               existing_type=sa.INTEGER(),
               comment='처리된 레코드 수',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'error_message',
               existing_type=sa.TEXT(),
               comment='에러 메시지 (실패 시)',
               existing_nullable=True)
    op.alter_column('batch_job_status', 'metadata_json',
               existing_type=sa.TEXT(),
               comment='작업 메타데이터 (JSON)',
               existing_nullable=True)
    op.create_table_comment(
        'batch_job_status',
        '배치 작업 실행 이력 및 상태',
        existing_comment=None,
        schema=None
    )
    op.alter_column('daily_performances', 'id',
               existing_type=sa.INTEGER(),
               comment='성과 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('daily_performances', 'user_id',
               existing_type=sa.INTEGER(),
               comment='사용자 ID (FK)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'record_date',
               existing_type=sa.DATE(),
               comment='기준일자',
               existing_nullable=False)
    op.alter_column('daily_performances', 'total_value_krw',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='총 평가금액 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'total_invested_krw',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='총 투자원금 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'kr_value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='한국 주식 평가금액 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'us_value_usd',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='미국 주식 평가금액 (USD)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'us_value_krw',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='미국 주식 평가금액 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='적용 환율 (USD/KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'daily_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='일일 손익 (전일 대비)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'daily_pnl_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='일일 수익률 (%)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'cumulative_return',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='누적 손익',
               existing_nullable=False)
    op.alter_column('daily_performances', 'cumulative_return_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='누적 수익률 (%)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'total_dividends',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='누적 배당금',
               existing_nullable=False)
    op.alter_column('daily_performances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='기록 생성일시',
               existing_nullable=False)
    op.create_table_comment(
        'daily_performances',
        '일별 포트폴리오 성과 추이',
        existing_comment=None,
        schema=None
    )
    op.alter_column('holdings', 'id',
               existing_type=sa.INTEGER(),
               comment='보유 종목 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('holdings', 'user_id',
               existing_type=sa.INTEGER(),
               comment='사용자 ID (FK)',
               existing_nullable=False)
    op.alter_column('holdings', 'stock_id',
               existing_type=sa.INTEGER(),
               comment='종목 ID (FK)',
               existing_nullable=False)
    op.alter_column('holdings', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='보유 수량',
               existing_nullable=False)
    op.alter_column('holdings', 'average_cost',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='평균 매수 단가',
               existing_nullable=False)
    op.alter_column('holdings', 'average_exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='평균 매수 환율',
               existing_nullable=False)
    op.alter_column('holdings', 'total_invested',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='총 투자금액 (KRW)',
               existing_nullable=False)
    op.alter_column('holdings', 'total_dividends',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='누적 배당금 (KRW)',
               existing_nullable=False)
    op.alter_column('holdings', 'realized_gain',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='실현 손익 (매도 확정 금액)',
               existing_nullable=False)
    op.alter_column('holdings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='최초 매수일시',
               existing_nullable=False)
    op.alter_column('holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='마지막 거래 반영일시',
               existing_nullable=False)
    op.create_table_comment(
        'holdings',
        '사용자별 보유 종목 현황 (포지션)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('market_data_history', 'id',
               existing_type=sa.INTEGER(),
               comment='시세 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('market_data_history', 'stock_id',
               existing_type=sa.INTEGER(),
               comment='종목 ID (FK)',
               existing_nullable=False)
    op.alter_column('market_data_history', 'record_date',
               existing_type=sa.DATE(),
               comment='기준일자',
               existing_nullable=False)
    op.alter_column('market_data_history', 'open_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='시가',
               existing_nullable=True)
    op.alter_column('market_data_history', 'high_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='고가',
               existing_nullable=True)
    op.alter_column('market_data_history', 'low_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='저가',
               existing_nullable=True)
    op.alter_column('market_data_history', 'close_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='종가',
               existing_nullable=False)
    op.alter_column('market_data_history', 'volume',
               existing_type=sa.INTEGER(),
               comment='거래량',
               existing_nullable=True)
    op.alter_column('market_data_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='데이터 수집일시',
               existing_nullable=False)
    op.create_table_comment(
        'market_data_history',
        '종목별 일별 시세 이력 (OHLCV)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('stocks', 'id',
               existing_type=sa.INTEGER(),
               comment='종목 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('stocks_id_seq'::regclass)"))
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               comment='종목 코드 (티커)',
               existing_nullable=False)
    op.alter_column('stocks', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='종목명',
               existing_nullable=False)
    op.alter_column('stocks', 'market_type',
               existing_type=postgresql.ENUM('KR', 'US', name='markettype'),
               comment='시장 구분 (KR/US)',
               existing_nullable=False)
    op.alter_column('stocks', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment='거래소 (KOSPI/NASDAQ 등)',
               existing_nullable=False)
    op.alter_column('stocks', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment='업종/섹터',
               existing_nullable=True)
    op.alter_column('stocks', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='현재가 (최근 업데이트 가격)',
               existing_nullable=True)
    op.alter_column('stocks', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment='통화 단위',
               existing_nullable=False)
    op.alter_column('stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='등록일시',
               existing_nullable=False)
    op.alter_column('stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='마지막 수정일시',
               existing_nullable=False)
    op.create_table_comment(
        'stocks',
        '주식 종목 마스터 정보',
        existing_comment=None,
        schema=None
    )
    op.alter_column('transactions', 'id',
               existing_type=sa.INTEGER(),
               comment='거래 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='사용자 ID (FK)',
               existing_nullable=False)
    op.alter_column('transactions', 'stock_id',
               existing_type=sa.INTEGER(),
               comment='종목 ID (FK)',
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'DIVIDEND', name='transactiontype'),
               comment='거래 유형 (BUY/SELL/DIVIDEND)',
               existing_nullable=False)
    op.alter_column('transactions', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='거래 수량',
               existing_nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='거래 단가',
               existing_nullable=False)
    op.alter_column('transactions', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='환율 (USD->KRW)',
               existing_nullable=False)
    op.alter_column('transactions', 'fees',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='수수료',
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.DATE(),
               comment='거래 일자',
               existing_nullable=False)
    op.alter_column('transactions', 'notes',
               existing_type=sa.VARCHAR(length=500),
               comment='메모',
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='등록일시',
               existing_nullable=False)
    op.create_table_comment(
        'transactions',
        '매매 거래 내역 (매수/매도)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='사용자 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일 (로그인 ID)',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='암호화된 비밀번호',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('users', 'base_currency',
               existing_type=postgresql.ENUM('KRW', 'USD', name='basecurrency'),
               comment='기준 통화 (KRW/USD)',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='계정 활성화 여부',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='계정 생성일시',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='마지막 수정일시',
               existing_nullable=False)
    op.create_table_comment(
        'users',
        '사용자 계정 정보',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='사용자 계정 정보',
        schema=None
    )
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 수정일시',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='계정 생성일시',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='계정 활성화 여부',
               existing_nullable=False)
    op.alter_column('users', 'base_currency',
               existing_type=postgresql.ENUM('KRW', 'USD', name='basecurrency'),
               comment=None,
               existing_comment='기준 통화 (KRW/USD)',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='암호화된 비밀번호',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='이메일 (로그인 ID)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_table_comment(
        'transactions',
        existing_comment='매매 거래 내역 (매수/매도)',
        schema=None
    )
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='등록일시',
               existing_nullable=False)
    op.alter_column('transactions', 'notes',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='메모',
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='거래 일자',
               existing_nullable=False)
    op.alter_column('transactions', 'fees',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='수수료',
               existing_nullable=False)
    op.alter_column('transactions', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='환율 (USD->KRW)',
               existing_nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='거래 단가',
               existing_nullable=False)
    op.alter_column('transactions', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='거래 수량',
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('BUY', 'SELL', 'DIVIDEND', name='transactiontype'),
               comment=None,
               existing_comment='거래 유형 (BUY/SELL/DIVIDEND)',
               existing_nullable=False)
    op.alter_column('transactions', 'stock_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='종목 ID (FK)',
               existing_nullable=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자 ID (FK)',
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='거래 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'stocks',
        existing_comment='주식 종목 마스터 정보',
        schema=None
    )
    op.alter_column('stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 수정일시',
               existing_nullable=False)
    op.alter_column('stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='등록일시',
               existing_nullable=False)
    op.alter_column('stocks', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='통화 단위',
               existing_nullable=False)
    op.alter_column('stocks', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='현재가 (최근 업데이트 가격)',
               existing_nullable=True)
    op.alter_column('stocks', 'sector',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='업종/섹터',
               existing_nullable=True)
    op.alter_column('stocks', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='거래소 (KOSPI/NASDAQ 등)',
               existing_nullable=False)
    op.alter_column('stocks', 'market_type',
               existing_type=postgresql.ENUM('KR', 'US', name='markettype'),
               comment=None,
               existing_comment='시장 구분 (KR/US)',
               existing_nullable=False)
    op.alter_column('stocks', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='종목명',
               existing_nullable=False)
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='종목 코드 (티커)',
               existing_nullable=False)
    op.alter_column('stocks', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='종목 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('stocks_id_seq'::regclass)"))
    op.drop_table_comment(
        'market_data_history',
        existing_comment='종목별 일별 시세 이력 (OHLCV)',
        schema=None
    )
    op.alter_column('market_data_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='데이터 수집일시',
               existing_nullable=False)
    op.alter_column('market_data_history', 'volume',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='거래량',
               existing_nullable=True)
    op.alter_column('market_data_history', 'close_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='종가',
               existing_nullable=False)
    op.alter_column('market_data_history', 'low_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='저가',
               existing_nullable=True)
    op.alter_column('market_data_history', 'high_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='고가',
               existing_nullable=True)
    op.alter_column('market_data_history', 'open_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='시가',
               existing_nullable=True)
    op.alter_column('market_data_history', 'record_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='기준일자',
               existing_nullable=False)
    op.alter_column('market_data_history', 'stock_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='종목 ID (FK)',
               existing_nullable=False)
    op.alter_column('market_data_history', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='시세 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'holdings',
        existing_comment='사용자별 보유 종목 현황 (포지션)',
        schema=None
    )
    op.alter_column('holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 거래 반영일시',
               existing_nullable=False)
    op.alter_column('holdings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='최초 매수일시',
               existing_nullable=False)
    op.alter_column('holdings', 'realized_gain',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='실현 손익 (매도 확정 금액)',
               existing_nullable=False)
    op.alter_column('holdings', 'total_dividends',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='누적 배당금 (KRW)',
               existing_nullable=False)
    op.alter_column('holdings', 'total_invested',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='총 투자금액 (KRW)',
               existing_nullable=False)
    op.alter_column('holdings', 'average_exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='평균 매수 환율',
               existing_nullable=False)
    op.alter_column('holdings', 'average_cost',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='평균 매수 단가',
               existing_nullable=False)
    op.alter_column('holdings', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='보유 수량',
               existing_nullable=False)
    op.alter_column('holdings', 'stock_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='종목 ID (FK)',
               existing_nullable=False)
    op.alter_column('holdings', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자 ID (FK)',
               existing_nullable=False)
    op.alter_column('holdings', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='보유 종목 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'daily_performances',
        existing_comment='일별 포트폴리오 성과 추이',
        schema=None
    )
    op.alter_column('daily_performances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='기록 생성일시',
               existing_nullable=False)
    op.alter_column('daily_performances', 'total_dividends',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='누적 배당금',
               existing_nullable=False)
    op.alter_column('daily_performances', 'cumulative_return_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='누적 수익률 (%)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'cumulative_return',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='누적 손익',
               existing_nullable=False)
    op.alter_column('daily_performances', 'daily_pnl_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='일일 수익률 (%)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'daily_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='일일 손익 (전일 대비)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='적용 환율 (USD/KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'us_value_krw',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='미국 주식 평가금액 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'us_value_usd',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='미국 주식 평가금액 (USD)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'kr_value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='한국 주식 평가금액 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'total_invested_krw',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='총 투자원금 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'total_value_krw',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='총 평가금액 (KRW)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'record_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='기준일자',
               existing_nullable=False)
    op.alter_column('daily_performances', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자 ID (FK)',
               existing_nullable=False)
    op.alter_column('daily_performances', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='성과 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'batch_job_status',
        existing_comment='배치 작업 실행 이력 및 상태',
        schema=None
    )
    op.alter_column('batch_job_status', 'metadata_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='작업 메타데이터 (JSON)',
               existing_nullable=True)
    op.alter_column('batch_job_status', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='에러 메시지 (실패 시)',
               existing_nullable=True)
    op.alter_column('batch_job_status', 'records_processed',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='처리된 레코드 수',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='작업 완료일시',
               existing_nullable=True)
    op.alter_column('batch_job_status', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='작업 시작일시',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'),
               comment=None,
               existing_comment='작업 상태 (PENDING/RUNNING/SUCCESS/FAILED)',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'job_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='작업명 (예: daily_pnl_calculation)',
               existing_nullable=False)
    op.alter_column('batch_job_status', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='작업 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('dividends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('tax', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('dividend_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('dividends_stock_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('dividends_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dividends_pkey'))
    )
    op.create_index(op.f('ix_dividends_user_id'), 'dividends', ['user_id'], unique=False)
    op.create_index(op.f('ix_dividends_stock_id'), 'dividends', ['stock_id'], unique=False)
    op.create_index(op.f('ix_dividends_dividend_date'), 'dividends', ['dividend_date'], unique=False)
    # ### end Alembic commands ###
