"""Add stock_daily_performances table

Revision ID: b7403b28bd9a
Revises: 86e220a2e6c0
Create Date: 2026-01-17 15:06:13.709387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7403b28bd9a'
down_revision: Union[str, None] = '86e220a2e6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
